version: '3.9'

services:
  db:
    container_name: database
    build:
      context: ./prisma
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - auth_network

networks:
  auth_network:
    name: auth_network
    driver: bridge
