name: Merge Branch

on:
  push:
    branches:
      - main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch Merge
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: "cicd"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
