name: Merge Branch

on:
  push:
    branches:
      - main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> cicd
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: cicd
          github_token: ${{ secrets.GITHUB_TOKEN }}
