name: CI/CD Pipeline

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkut source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MyFesko.DOCKER_USERNAME }}
          password: ${{ secrets.MyFesko.DOCKER_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.MyFesko.DOCKER_USERNAME }}/myfesko .
      - name: Push Docker Image
        run: docker push ${{ secrets.MyFesko.DOCKER_USERNAME }}/myfesko:latest

  deploy:
    needs: build
    runs-on: [myfesko-server]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.MyFesko.DOCKER_USERNAME }}/myfesko:latest
      - name: Run Docker Container
        run: docker run -d -p ${{ secrets.MyFesko.NEXTJS_PORT }}:${{ secrets.MyFesko.NEXTJS_PORT }} --name myfesko-web ${{ secrets.MyFesko.DOCKER_USERNAME }}/myfesko:latest
