name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> cicd
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: cicd
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    environment: MyFesko
    steps:
      - name: Checkut source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myfesko .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myfesko:latest

  deploy:
    needs: build
    runs-on: [myfesko-server]
    environment: MyFesko
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/myfesko:latest
      - name: Run Docker Container
        run: |
          docker run -d -p 9005:9005 \
          -e DIRECT_AUTH_DATABASE_URL=${{ secrets.DIRECT_AUTH_DATABASE_URL }} \
          -e DIRECT_CHAT_DATABASE_URL=${{ secrets.DIRECT_CHAT_DATABASE_URL }} \
          -e DATABASE_URL_ACCELERATE=${{ secrets.DATABASE_URL_ACCELERATE }} \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -e NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY=${{ secrets.NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY }} \
          -e CLOUDFLARE_TURNSTILE_SECRET_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }} \
          -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
          -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
          -e SMTP_GMAIL_EMAIL=${{ secrets.SMTP_GMAIL_EMAIL }} \
          -e SMTP_GMAIL_PASSWORD=${{ secrets.SMTP_GMAIL_PASSWORD }} \
          -e JWT_USER_ID_SECRET=${{ secrets.JWT_USER_ID_SECRET }} \
          -e AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }} \
          -e AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }} \
          -e WEBSOCKET_PORT=${{ secrets.WEBSOCKET_PORT }} \
          --name myfesko-web ${{ secrets.DOCKER_USERNAME }}/myfesko:latest
